Use script name to create directory, rather than adding to the file name

diff --git a/scripts/slurm-sbatch b/scripts/slurm-sbatch
--- a/scripts/slurm-sbatch
+++ b/scripts/slurm-sbatch
@@ -63,7 +63,13 @@ if [[ -z "$SLURM_SCRIPT" ]]; then
 fi
 
 # Convert relative paths to absolute paths if necessary
-LOG_DIR_SHORT="$LOG_DIR"
+SANITIZED_SCRIPT_NAME=$(basename "$SLURM_SCRIPT" .sh | tr -cd '[:alnum:]_-')
+if [ -z "$SANITIZED_SCRIPT_NAME" ]; then
+    echo "Error: Invalid script name."
+    echo "Sanitized script name was empty."
+    exit 1
+fi
+LOG_DIR_SHORT="$LOG_DIR/$SANITIZED_SCRIPT_NAME"
 if [[ ! "$LOG_DIR" = /* ]]; then
     LOG_DIR="$WD/$LOG_DIR"
 fi
@@ -99,8 +105,7 @@ fi
 
 # Generate the log file name based on the current date and time
 LOG_FILE_TIME=$(date '+%Y-%m-%d_%H-%M-%S')
-SANITIZED_SCRIPT_NAME=$(basename "$SLURM_SCRIPT" .sh | tr -cd '[:alnum:]_-')
-LOG_FILE_BASENAME="run_$SANITIZED_SCRIPT_NAME_${LOG_FILE_TIME}_out.txt"
+LOG_FILE_BASENAME="run_${LOG_FILE_TIME}_out.txt"
 LOG_FILE_SHORT="$LOG_DIR_SHORT/$LOG_FILE_BASENAME"
 LOG_FILE="$LOG_DIR/$LOG_FILE_BASENAME"
 
@@ -108,7 +113,7 @@ if [[ -f "$LOG_FILE" ]]; then
     rm "$LOG_FILE"
 fi
 
-LOG_FILE_SCRIPT_BASENAME="run_$SANITIZED_SCRIPT_NAME_${LOG_FILE_TIME}_script.txt"
+LOG_FILE_SCRIPT_BASENAME="run_${LOG_FILE_TIME}_script.txt"
 LOG_FILE_SCRIPT_SHORT="$LOG_DIR_SHORT/$LOG_FILE_SCRIPT_BASENAME"
 LOG_FILE_SCRIPT="$LOG_DIR/$LOG_FILE_SCRIPT_BASENAME"
 
