Update GHA

diff --git a/.github/workflows/fork-update.yml b/.github/workflows/fork-update.yml
--- a/.github/workflows/fork-update.yml
+++ b/.github/workflows/fork-update.yml
@@ -56,7 +56,7 @@ jobs:
           # Perform the merge
           git config --local user.email "actions@github.com"
           git config --local user.name "GitHub Actions"
-          git merge -X theirs upstream/main -m "Merged upstream changes, favouring upstream in case of conflicts" || echo "Automatic merge failed, manual intervention required!" > /tmp/merge_status.txt
+          git merge -X theirs upstream/main -m "Merged upstream changes, favouring upstream in case of conflicts" > /tmp/merge_output.txt 2>&1 || echo "Automatic merge failed, manual intervention required!" > /tmp/merge_status.txt
 
           # Check for differences after merge
           git diff main > /tmp/after_merge.diff
@@ -75,9 +75,9 @@ jobs:
       - name: Handle Merge Conflicts
         run: |
           if [ -f /tmp/merge_status.txt ]; then
+            cat /tmp/merge_output.txt
             echo "Merge conflicts detected. Creating branch for manual merge."
             git checkout -b unmerged-changes-satvilab upstream/main
-            git push origin unmerged-changes-satvilab
             echo "MERGE_STATUS=failure" >> $GITHUB_ENV
           else
             echo "Merge successful."
