Update GHA

diff --git a/.github/workflows/fork-update.yml b/.github/workflows/fork-update.yml
--- a/.github/workflows/fork-update.yml
+++ b/.github/workflows/fork-update.yml
@@ -47,19 +47,18 @@ jobs:
           git fetch upstream main
 
       - name: Merge Upstream Changes
-
         run: |
-          git checkout -b merged-changes-satvilab origin/main
+          git checkout -b merged-changes-satvilab
           echo "Attempting to merge 'upstream/main' into 'merged-changes-satvilab'"
           
           # Save the current state
-          git diff origin/main > /tmp/before_merge.diff
+          git diff main > /tmp/before_merge.diff
 
           # Perform the merge
-          git merge -X theirs upstream/main || echo "Automatic merge failed, manual intervention required!" > merge_status.txt
+          git merge -X theirs upstream/main -m "Merged upstream changes, favouring upstream in case of conflicts" || echo "Automatic merge failed, manual intervention required!" > merge_status.txt
 
           # Check for differences after merge
-          git diff origin/main > /tmp/after_merge.diff
+          git diff main > /tmp/after_merge.diff
 
       - name: Check Merge Status
         run: |
